//actions
export const ACTION_NOTIFICATION = 'ACTION_NOTIFICATION';
export const ACTION_NEW_SUB = 'ACTION_NEW_SUB';
export const ACTION_SET_CURRENT_SUB = 'ACTION_SET_CURRENT_SUB';
export const ACTION_GET_POSTS = 'ACTION_GET_POSTS';
export const ACTION_SET_POSTS = 'ACTION_SET_POSTS';
export const ACTION_CURRENT_POST = 'ACTION_CURRENT_POST';
export const ACTION_SHOW_LOADER = 'ACTION_SHOW_LOADING';
export const ACTION_HIDE_LOADER = 'ACTION_HIDE_LOADER';
export const ACTION_SET_LAST_POST = 'SET_LAST_POST';
export const ACTION_SET_FOLLOWUP = 'ACTION_SET_FOLLOWUP';